### ISSUE TITLE
Only support left and right

### ISSUE THREAD

**Issue by K232** [rranjithkumar100/Xamarin-Swipe-Library#1]
First: Thanks for the solution!

I'd like to use it within a scrollview which works fine in general, but I only want to take care about the left and right swipe. Top and Bottom swipe should act as normal in the scrollview (means it should scroll up and down). 

Is it possible to achieve that?

Many thanks in advance!

**Comment by msmith1992** [comment]
I would like to be able to achieve this too, was there any progress on it?

Many Thanks

**Comment by K232** [comment]
@msmith1992 , as @rranjithkumar100 did not reply for more than a month, I'm now using https://github.com/alexrainman/CarouselView which works fine also with scrollviews. Maybe have a look at it.
